=== yaozhuan/siseplatform/APDPlat_Module/src/main/resources/META-INF/services/dic.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/dic.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE dic SYSTEM "dic.dtd">

    <dic>
    ...
    </dic>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dic (dicItems|subDics)*>
<!ATTLIST dic
    justCode CDATA #IMPLIED
    chinese CDATA #IMPLIED
    english CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT subDics (dic)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dicItems (dicItem)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dicItem EMPTY>
<!ATTLIST dicItem
    name CDATA #IMPLIED
    code CDATA #IMPLIED
  >

=== yaozhuan/siseplatform/APDPlat_Core/src/main/resources/META-INF/services/dic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dic SYSTEM "dic.dtd">
<!--
        业务字典XML文件
        在本文件中的先后顺序就是在下拉菜单中的顺序
-->
<dic  english="root" chinese="数据字典">
    <subDics>
        <dic english="security" chinese="安全管理">   
            <subDics>                
                <dic english="userState" chinese="用户状态" justCode="true">
                    <dicItems>
                        <dicItem code="true" name="启用"/>
                        <dicItem code="false" name="停用"/>
                    </dicItems>
                </dic>
            </subDics>
        </dic>
    </subDics>
</dic>
